---
openapi: 3.0.0
info:
  title: Sistema de Inscripciones UPTC V2
  description: Este es un ejemplo para crear inscripciones creado para la materia de Sistemas Distribuidos 2022 UPTC
  contact:
    name: Ronald Johan Pineda
    email: ronald.pineda01@uptc.edu.co
  version: 1.0.0
externalDocs:
  description: 'GitHub '
  url: https://github.com/keos14/SistemaIncripcionDeMaterias
servers:
- url: https://localhost:4000
  description: |
    Servidor principal y local de manejo de materias
tags:
- name: Usuarios
  description: Secured Admin-only calls
- name: Inscripciones
  description: Operations available to regular developers
- name: Materias
paths:
  /api/users/{id}:
    get:
      tags:
      - Usuarios
      summary: Obtener Usuario.
      description: |
        Trae información del usuario registrado con el id.
      operationId: getUser
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuarios'
        "500":
          description: Error Interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
    put:
      tags:
      - Usuarios
      summary: Editar Usuario
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuarios'
            example:
              id_usuario: 1221-2
              numero_documento: Jessica Smith
              nombre_usuario: Pedro andres
              apellido_usuario: Ariza
              tipo_documento: CC
              codigo: 213123123
              estado: 1
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. Please fill all fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
                message: Bad request. Please fill all fields.
        "500":
          description: Error Interno.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
  /api/users/:
    get:
      tags:
      - Usuarios
      summary: Obtener Usuarios.
      description: |
        Trae información del usuario registrado con el id.
      operationId: getUsers
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuarios'
        "500":
          description: Error Interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
    post:
      tags:
      - Usuarios
      summary: Adds a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuarios'
            example:
              id_usuario: 1221-2
              numero_documento: Jessica Smith
              nombre_usuario: Pedro andres
              apellido_usuario: Ariza
              tipo_documento: CC
              codigo: 213123123
              estado: 1
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. Please fill all fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
                message: Bad request. Please fill all fields.
        "500":
          description: Error Interno.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
  /api/subjects/:
    get:
      tags:
      - Materias
      summary: Obtener Materias.
      description: |
        Trae información de las materias existentes.
      operationId: getSubjects
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Materias'
        "500":
          description: Error Interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
    post:
      tags:
      - Materias
      summary: Adds a new Subjects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Materias'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. Please fill all fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
                message: Bad request. Please fill all fields.
        "500":
          description: Error Interno.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
  /api/subjects/{id}:
    get:
      tags:
      - Materias
      summary: Obtener Materia.
      description: |
        Trae información de la mateira registrado con el id.
      operationId: getSubject
      parameters:
      - name: id
        in: path
        description: Subject ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Materias'
        "500":
          description: Error Interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
    put:
      tags:
      - Materias
      summary: Editar Materia
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Materias'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. Please fill all fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
                message: Bad request. Please fill all fields.
        "500":
          description: Error Interno.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
  /api/inscriptions/:
    get:
      tags:
      - Inscripciones
      summary: Obtener Materias.
      description: |
        Trae información de las materias existentes.
      operationId: getInscriptions
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inscripciones'
        "500":
          description: Error Interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
    post:
      tags:
      - Inscripciones
      summary: Adds a new Inscription
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Inscripciones'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. Please fill all fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
                message: Bad request. Please fill all fields.
        "500":
          description: Error Interno.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
  /api/inscriptions/{id}:
    get:
      tags:
      - Inscripciones
      summary: Obtener Materia.
      description: |
        Trae información de la inscripcion registrado con el id.
      operationId: getInscription
      parameters:
      - name: id
        in: path
        description: Inscripciones ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inscripciones'
        "500":
          description: Error Interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
    put:
      tags:
      - Inscripciones
      summary: Editar Materia
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Materias'
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. Please fill all fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
                message: Bad request. Please fill all fields.
        "500":
          description: Error Interno.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/msg_error'
              example:
                type: 400
components:
  schemas:
    Usuarios:
      required:
      - apellido_usuario
      - codigo
      - estado
      - id_usuario
      - nombre_usuario
      - numero_documento
      - tipo_documento
      type: object
      properties:
        id_usuario:
          type: string
          example: Pedro Andres
        numero_documento:
          type: string
          example: "15151565165"
        nombre_usuario:
          type: string
          example: Pepe T1
        apellido_usuario:
          type: string
          example: Perez T2
        tipo_documento:
          type: string
          example: CC
        codigo:
          type: string
          example: "123123123"
        estado:
          type: string
          example: A
    Materias:
      required:
      - codigo_materia
      - creditos
      - es_habilitable
      - estado VARCHAR
      - id_materia
      - nombre_materia
      type: object
      properties:
        id_materia:
          type: string
          example: Sistemas Distribuidos
        creditos:
          type: integer
          example: 4
        codigo_materia:
          type: integer
          example: 10000075
        estado:
          type: string
          example: A
        es_habilitable:
          type: string
          example: SI
    Cursos:
      required:
      - Materia_id_materia
      - cupos
      - estado
      - fecha_fin
      - fecha_inicio
      - id_curso
      type: object
      properties:
        id_curso:
          type: integer
          example: 123467972
        cupos:
          type: integer
          example: 1
        fecha_inicio:
          type: string
          example: 10/08/2020
        fecha_fin:
          type: string
          example: 10/08/2020
        estado:
          type: string
          example: A
        Materia_id_materia:
          type: integer
          example: 10000075
    Inscripciones:
      required:
      - Curso_id_curso
      - Usuario_id_usuario
      - id_inscripcion
      - nota_habilitacion
      - nota_primer_corte
      - nota_segundo_corte
      type: object
      properties:
        id_inscripcion:
          type: integer
          example: 2020215156
        nota_primer_corte:
          type: integer
        nota_segundo_corte:
          type: integer
        nota_habilitacion:
          type: integer
        Usuario_id_usuario:
          type: integer
          example: 201910075
        Curso_id_curso:
          type: integer
          example: 123456789
    msg_error:
      type: object
      properties:
        type:
          type: integer
          example: 500
        message:
          type: string
          example: Error interno de la DB
